# Generated by Django 3.1.4 on 2021-02-15 22:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrubchenOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=500)),
                ('text', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Oferenda de Drubchen',
                'verbose_name_plural': 'Oferendas de Drubchen',
                'ordering': ['-id'],
            },
        ),
    ]
