# Generated by Django 3.1.4 on 2021-01-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('vajra_master', models.CharField(max_length=200)),
                ('requirements', models.CharField(blank=True, max_length=1000, null=True)),
                ('place', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=20000)),
                ('short_description', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
