# Generated by Django 3.1.4 on 2021-01-17 03:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participation_text',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
