# Generated by Django 3.1.4 on 2021-01-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20210117_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('online', 'Online'), ('presential', 'Presencial')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='amitaba_accommodation_capacity',
            field=models.PositiveIntegerField(verbose_name='Lotação Amitaba'),
        ),
        migrations.AlterField(
            model_name='event',
            name='amitaba_accommodation_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço Amitaba'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dormitory_accommodation_capacity',
            field=models.PositiveIntegerField(verbose_name='Lotação dormitório'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dormitory_accommodation_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço dormitório'),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_accommodation_capacity',
            field=models.PositiveIntegerField(verbose_name='Lotação sem acomodação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_accommodation_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço sem acomodação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='retreat_house_accommodation_capacity',
            field=models.PositiveIntegerField(verbose_name='Lotação casa de retiro'),
        ),
        migrations.AlterField(
            model_name='event',
            name='retreat_house_accommodation_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço casa de retiro'),
        ),
    ]
