# Generated by Django 3.1.4 on 2021-01-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cielo_link',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
