# Generated by Django 3.1.4 on 2021-02-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_cielo_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
