# Generated by Django 3.1.4 on 2021-03-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
