# Generated by Django 3.1.4 on 2021-03-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20210320_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço do evento online'),
        ),
        migrations.AlterField(
            model_name='event',
            name='amitaba_accommodation_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lotação Amitaba'),
        ),
        migrations.AlterField(
            model_name='event',
            name='amitaba_accommodation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço Amitaba'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dormitory_accommodation_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lotação dormitório'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dormitory_accommodation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço dormitório'),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_accommodation_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lotação sem acomodação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='no_accommodation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço sem acomodação'),
        ),
        migrations.AlterField(
            model_name='event',
            name='retreat_house_accommodation_capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lotação casa de retiro'),
        ),
        migrations.AlterField(
            model_name='event',
            name='retreat_house_accommodation_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço casa de retiro'),
        ),
    ]
