# Generated by Django 3.1.4 on 2021-05-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20210321_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CieloLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Link Cielo',
                'verbose_name_plural': 'Links Cielo',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='cielo_link',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('online', 'On-line'), ('presential', 'Presencial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='online_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço do evento on-line'),
        ),
        migrations.AddField(
            model_name='event',
            name='cielo_link',
            field=models.ManyToManyField(to='event.CieloLinks'),
        ),
    ]
