# Generated by Django 3.1.4 on 2021-05-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20210523_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='paypal_link',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
