# Generated by Django 3.1.4 on 2021-05-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_event_paypal_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cielolinks',
            old_name='valor',
            new_name='value',
        ),
    ]
