# Generated by Django 3.1.4 on 2021-05-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20210523_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cielolinks',
            name='value',
        ),
        migrations.AddField(
            model_name='cielolinks',
            name='title',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
