# Generated by Django 3.0.8 on 2020-08-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khadro_ling', '0004_auto_20200802_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.TextField(default='a', max_length=1000),
            preserve_default=False,
        ),
    ]
