# Generated by Django 3.1.4 on 2021-01-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khadro_ling', '0005_event_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offering',
        ),
    ]
