# Generated by Django 3.1.4 on 2021-01-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khadro_ling', '0006_delete_offering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
