# Generated by Django 3.1.4 on 2021-01-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20210110_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Novidade', 'verbose_name_plural': 'Novidades'},
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
    ]
