# Generated by Django 3.1.4 on 2021-01-10 16:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_auto_20210110_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
