# Generated by Django 3.1.4 on 2021-01-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_auto_20210110_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
