# Generated by Django 3.1.4 on 2021-01-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_auto_20210110_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'Novidade', 'verbose_name_plural': 'Novidades'},
        ),
    ]
