# Generated by Django 3.1.4 on 2021-02-15 15:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0006_auto_20210117_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='SacredDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('text', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name': 'Datas Sagradas',
                'verbose_name_plural': 'Datas Sagradas',
            },
        ),
    ]
