# Generated by Django 3.1.4 on 2021-02-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0008_genericpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
